version: '2'

services:
  proxy:
        build: ./src
        command: bash -c "./run.sh"
        volumes:
          - ./src:/code
          - ./logs:/var/log/erss
        ports:
          - "12345:12345"
        tty: true